version: 2.1

jobs:
  # Say Hello Job
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say Hello"
          command: "echo Hello, World!"

workflows:
  version: 2
  main-workflow:
    jobs:
      - say-hello
      - sonar_analysis:
          requires:
            - say-hello
