version: 2.1

jobs:
  # Say Hello Job
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say Hello"
          command: "echo Hello, World!"

  # SonarQube Analysis Job
  sonar_analysis:
    docker:
      - image: cimg/openjdk:17.0  # Ensure Java 17 is used
    steps:
      - checkout
      - run:
          name: Install SonarQube Scanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip
            export PATH=$(pwd)/sonar-scanner-4.6.2.2472-linux/bin:$PATH
            echo $PATH
            ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner --version

workflows:
  version: 2
  main-workflow:
    jobs:
      - say-hello

          requires:
            - say-hello
